<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUPCUHi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUPCUHi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSUPCUHi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSUPCUHi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSUPCUHi\App_KernelDevDebugContainer([
    'container.build_hash' => 'SUPCUHi',
    'container.build_id' => '54663342',
    'container.build_time' => 1683278898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUPCUHi');
