<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjMwiCb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjMwiCb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWjMwiCb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWjMwiCb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWjMwiCb\App_KernelDevDebugContainer([
    'container.build_hash' => 'WjMwiCb',
    'container.build_id' => '215586e1',
    'container.build_time' => 1683274932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjMwiCb');
