<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerENzwPtv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerENzwPtv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerENzwPtv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerENzwPtv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerENzwPtv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ENzwPtv',
    'container.build_id' => 'f4bc392d',
    'container.build_time' => 1683298997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerENzwPtv');
